version: "3"
services:
  react-app:
    image: tunein-client
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - mern-app
    volumes:
      - "./client:/usr/src/app"
  api-server:
    image: api-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - mern-app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - mongo
    volumes:
      - "./server:/usr/src/app/server"
  mongo:
    image: mongo:3.6.19-xenial
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
  # mongo-seed:
  #   image: mongo:3.6.19-xenial
  #   volumes:
  #     - ./mongo-seed:/mongo-seed
  #   command:
  #     ./mongo-seed/import.sh
  #   networks:
  #     - mern-app
  #   links:
  #     - mongo
  #   depends_on:
  #     - mongo
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
  mongo-config: {}
